In [1]:
!wget https://raw.githubusercontent.com/JWarmenhoven/ISLR-python/master/Notebooks/Data/Advertising.csv

--2020-08-28 04:51:18--  https://raw.githubusercontent.com/JWarmenhoven/ISLR-python/master/Notebooks/Data/Advertising.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5166 (5.0K) [text/plain]
Saving to: ‘Advertising.csv’

Advertising.csv     100%[===================>]   5.04K  --.-KB/s    in 0s

2020-08-28 04:51:18 (58.8 MB/s) - ‘Advertising.csv’ saved [5166/5166]

In [2]:
import pandas as pd
df = pd.read_csv('Advertising.csv')
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
import numpy as np
df['Sales Type'] = np.where(df['Sales'] < 15, np.where(df['Sales'] < 5, 'Low', 'Medium'), 'High')
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales Sales Type
0           1  230.1   37.8       69.2   22.1       High
1           2   44.5   39.3       45.1   10.4     Medium
2           3   17.2   45.9       69.3    9.3     Medium
3           4  151.5   41.3       58.5   18.5       High
4           5  180.8   10.8       58.4   12.9     Medium

In [4]:
print(df.groupby(['Sales Type']).sum())
print(df.groupby(['Sales Type']).mean())

            Unnamed: 0       TV   Radio  Newspaper   Sales
Sales Type
High              7510  16469.8  2594.1     2720.6  1500.8
Low                296     13.4    53.3       15.4     9.6
Medium           12294  12925.3  2005.4     3374.8  1294.1
            Unnamed: 0          TV      Radio  Newspaper      Sales
Sales Type
High         97.532468  213.893506  33.689610  35.332468  19.490909
Low          98.666667    4.466667  17.766667   5.133333   3.200000
Medium      102.450000  107.710833  16.711667  28.123333  10.784167

In [5]:
df.pivot(index='TV', columns='Radio', values='Radio')

Radio  0.0   0.3   0.4   0.8   1.3   1.4   ...  47.7  47.8  48.9  49.0  49.4  49.6
TV                                         ...
0.7     NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
4.1     NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
5.4     NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
7.3     NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
7.8     NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
289.7   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
290.7   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
292.9   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
293.6   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
296.4   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN

[190 rows x 167 columns]

In [6]:
for index, row in df.iterrows():
  if (index != 'TV' and int(index)%6 == 0):
    df.iloc[index]['TV'] = 'NULL'
for index, row in df.iterrows():
  if (index != 'TV' and int(index)%10 == 0):
    df.iloc[index]['Newspaper'] = float(0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [7]:
df[::6]

     Unnamed: 0     TV  Radio  Newspaper  Sales Sales Type
0             1  230.1   37.8       69.2   22.1       High
6             7   57.5   32.8       23.5   11.8     Medium
12           13   23.8   35.1       65.9    9.2     Medium
18           19   69.2   20.5       18.3   11.3     Medium
24           25   62.3   12.6       18.3    9.7     Medium
30           31  292.9   28.3       43.2   21.4       High
36           37  266.9   43.8        5.0   25.4       High
42           43  293.6   27.7        1.8   20.7       High
48           49  227.2   15.8       49.9   14.8     Medium
54           55  262.7   28.8       15.9   20.2       High
60           61   53.5    2.0       21.4    8.1     Medium
66           67   31.5   24.6        2.2    9.5     Medium
72           73   26.8   33.0       19.3    8.8     Medium
78           79    5.4   29.9        9.4    5.3     Medium
84           85  213.5   43.0       33.8   21.7       High
90           91  134.3    4.9        9.3   11.2     Medium
96           97  197.6    3.5        5.9   11.7     Medium
102         103  280.2   10.1       21.4   14.8     Medium
108         109   13.1    0.4       25.6    5.3     Medium
114         115   78.2   46.8       34.5   14.6     Medium
120         121  141.3   26.8       46.2   15.5       High
126         127    7.8   38.9       50.6    6.6     Medium
132         133    8.4   27.2        2.1    5.7     Medium
138         139   43.0   25.9       20.5    9.6     Medium
144         145   96.2   14.8       38.9   11.4     Medium
150         151  280.7   13.9       37.0   16.1       High
156         157   93.9   43.5       50.5   15.3       High
162         163  188.4   18.1       25.6   14.9     Medium
168         169  215.4   23.6       57.6   17.1       High
174         175  222.4    3.4       13.1   11.5     Medium
180         181  156.6    2.6        8.3   10.5     Medium
186         187  139.5    2.1       26.6   10.3     Medium
192         193   17.2    4.1       31.6    5.9     Medium
198         199  283.6   42.0       66.2   25.5       High

In [8]:
df[::10]

     Unnamed: 0     TV  Radio  Newspaper  Sales Sales Type
0             1  230.1   37.8       69.2   22.1       High
10           11   66.1    5.8       24.2    8.6     Medium
20           21  218.4   27.7       53.4   18.0       High
30           31  292.9   28.3       43.2   21.4       High
40           41  202.5   22.3       31.6   16.6       High
50           51  199.8    3.1       34.6   11.4     Medium
60           61   53.5    2.0       21.4    8.1     Medium
70           71  199.1   30.6       38.7   18.3       High
80           81   76.4   26.7       22.3   11.8     Medium
90           91  134.3    4.9        9.3   11.2     Medium
100         101  222.4    4.3       49.8   11.7     Medium
110         111  225.8    8.2       56.5   13.4     Medium
120         121  141.3   26.8       46.2   15.5       High
130         131    0.7   39.6        8.7    1.6        Low
140         141   73.4   17.0       12.9   10.9     Medium
150         151  280.7   13.9       37.0   16.1       High
160         161  172.5   18.1       30.7   14.4     Medium
170         171   50.0   11.6       18.4    8.4     Medium
180         181  156.6    2.6        8.3   10.5     Medium
190         191   39.5   41.1        5.8   10.8     Medium

In [9]:
for index, row in df.iterrows():
  if (index != 'TV' and int(index)%6 == 0):
    df.iloc[index]['TV'] = '0'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
df[::6]

     Unnamed: 0     TV  Radio  Newspaper  Sales Sales Type
0             1  230.1   37.8       69.2   22.1       High
6             7   57.5   32.8       23.5   11.8     Medium
12           13   23.8   35.1       65.9    9.2     Medium
18           19   69.2   20.5       18.3   11.3     Medium
24           25   62.3   12.6       18.3    9.7     Medium
30           31  292.9   28.3       43.2   21.4       High
36           37  266.9   43.8        5.0   25.4       High
42           43  293.6   27.7        1.8   20.7       High
48           49  227.2   15.8       49.9   14.8     Medium
54           55  262.7   28.8       15.9   20.2       High
60           61   53.5    2.0       21.4    8.1     Medium
66           67   31.5   24.6        2.2    9.5     Medium
72           73   26.8   33.0       19.3    8.8     Medium
78           79    5.4   29.9        9.4    5.3     Medium
84           85  213.5   43.0       33.8   21.7       High
90           91  134.3    4.9        9.3   11.2     Medium
96           97  197.6    3.5        5.9   11.7     Medium
102         103  280.2   10.1       21.4   14.8     Medium
108         109   13.1    0.4       25.6    5.3     Medium
114         115   78.2   46.8       34.5   14.6     Medium
120         121  141.3   26.8       46.2   15.5       High
126         127    7.8   38.9       50.6    6.6     Medium
132         133    8.4   27.2        2.1    5.7     Medium
138         139   43.0   25.9       20.5    9.6     Medium
144         145   96.2   14.8       38.9   11.4     Medium
150         151  280.7   13.9       37.0   16.1       High
156         157   93.9   43.5       50.5   15.3       High
162         163  188.4   18.1       25.6   14.9     Medium
168         169  215.4   23.6       57.6   17.1       High
174         175  222.4    3.4       13.1   11.5     Medium
180         181  156.6    2.6        8.3   10.5     Medium
186         187  139.5    2.1       26.6   10.3     Medium
192         193   17.2    4.1       31.6    5.9     Medium
198         199  283.6   42.0       66.2   25.5       High

In [11]:
for index, row in df.iterrows():
  if (index != 'TV' and int(index)%10 == 0):
    df.iloc[index]['Newspaper'] = sum(df['Newspaper'].values.tolist()[:-2])/len(df['Newspaper'].values.tolist()[:-2])

df[::10]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

     Unnamed: 0     TV  Radio  Newspaper  Sales Sales Type
0             1  230.1   37.8       69.2   22.1       High
10           11   66.1    5.8       24.2    8.6     Medium
20           21  218.4   27.7       53.4   18.0       High
30           31  292.9   28.3       43.2   21.4       High
40           41  202.5   22.3       31.6   16.6       High
50           51  199.8    3.1       34.6   11.4     Medium
60           61   53.5    2.0       21.4    8.1     Medium
70           71  199.1   30.6       38.7   18.3       High
80           81   76.4   26.7       22.3   11.8     Medium
90           91  134.3    4.9        9.3   11.2     Medium
100         101  222.4    4.3       49.8   11.7     Medium
110         111  225.8    8.2       56.5   13.4     Medium
120         121  141.3   26.8       46.2   15.5       High
130         131    0.7   39.6        8.7    1.6        Low
140         141   73.4   17.0       12.9   10.9     Medium
150         151  280.7   13.9       37.0   16.1       High
160         161  172.5   18.1       30.7   14.4     Medium
170         171   50.0   11.6       18.4    8.4     Medium
180         181  156.6    2.6        8.3   10.5     Medium
190         191   39.5   41.1        5.8   10.8     Medium

Regression Fit

In [12]:
df = pd.read_csv('Advertising.csv')
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [18]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(df[['TV', 'Radio', 'Newspaper', 'Sales']].values, df.Sales.values)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.coef_

array([-2.67075240e-17,  0.00000000e+00,  1.11022302e-16,  1.00000000e+00])